# Generated by Django 5.0.2 on 2025-03-03 15:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('currency', models.CharField(max_length=40)),
                ('imageSrc', models.ImageField(upload_to='uploads/shops')),
                ('imageAlt', models.CharField(max_length=155)),
            ],
        ),
    ]
